---
name: Build API/client files

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          node-version: "20"

      - name: Clean install dependencies and build
        env:
          TEST_WEB_HOST: "${{ secrets.TEST_WEB_HOST || 'https://localhost' }}"
        run: |
          npm ci
          npm run build

      - name: Upload build as artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        if: always()
        with:
          name: build-files
          path: |
            api/build
            api/package-lock.json
            api/package.json
            client/build
            client/package-lock.json
            client/package.json
            package-lock.json
            package.json
