---
name: Build API/client files

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/workflows/**"
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          node-version: "18"

      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Upload build as artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        if: always()
        with:
          name: build-files
          path: |
            ./api/build
            ./client/build
