---
name: Build and push Docker image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push the Docker image
        run: |
          docker build . -f Dockerfile -t ghcr.io/bitwarden/test-the-web:latest
          docker push ghcr.io/bitwarden/test-the-web:latest
